export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as HeroSlide } from './HeroSlide/HeroSlide';
export { default as Footer } from './Footer/Footer';
export { default as Modal } from './Modal/Modal';
export { default as ModalContent } from './Modal/ModalContent';
export { default as TrailerModal } from './Modal/TrailerModal';
export { default as Button } from './Button/Button';
export { default as MovieList } from './MovieList/MovieList';
